server:
  port: 8084

spring:
  application:
    name: emp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    instances:
      departmentServiceProxy:
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        minimumNumberOfCalls: 5