server:
    port: 8082

spring:
    application:
        name: order-service

    datasource:
        url: jdbc:mysql://localhost:3306/orderdb
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

# Eureka Client Configuration
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

    instance:
        prefer-ip-address: true
        hostname: localhost

# Resilience4j Circuit Breaker Configuration
resilience4j:
    circuitbreaker:
        instances:
            productService:
                registerHealthIndicator: true
                slidingWindowSize: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 5000ms
                permittedNumberOfCallsInHalfOpenState: 2
                automaticTransitionFromOpenToHalfOpenEnabled: true
                minimumNumberOfCalls: 5
                slowCallRateThreshold: 50
                slowCallDurationThreshold: 2000ms
