server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-ms-1
#          predicates:
#            - Path=/products/**
#
#        - id: order-service
#          uri: lb://order-ms-2
#          predicates:
#            - Path=/orders/**
#
#        - id: payment-service
#          uri: lb://payment-ms-3
#          predicates:
#            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
