server:
  port: 9000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


#  cloud:
#    gateway:
#      routes:
#        - id: emp-service
#          uri: lb://EMP
#          predicates:
#            - Path=/emp/**
#
#        - id: dept-service
#          uri: lb://DEPTAPP
#          predicates:
#            - Path=/dept/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

