version: "3.8"
services:
  product-service:
    build: ./docker_compose_product  # ✅ Match actual directory name
    image: manasshah24/product-service
    container_name: product-service
    ports:
      - "8082:8082"

  order-service:
    build: ./docker_compose_order  # ✅ Match actual directory name
    image: manasshah24/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - product-service
