apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-docker
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
        - name: hello-docker-container
          image: manasshah24/hello_docker:latest
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"